#!/bin/bash

# Hyperion Task Template

set -e

# ##########################################################################
# MODULE DEPENDENCIES
# Please ensure you're loading all required modules here.
# ##########################################################################

source /usr/local/modules-3.2.10/init/bash

module load cuda/7.0
module load mpi/openmpi/1.8.2
module load gasnet/1.22.4-openmpi

# ##########################################################################
# COMPILATION STAGE
# You're in the root folder of the legion runtime
# Clean your build target or you might be running an outdated build
# ##########################################################################

MAKE_FLAGS="DEBUG=0 SHARED_LOWLEVEL=0 USE_GASNET=1 USE_CUDA=1 -DLEGION_PROF"

cd examples/full_circuit
LG_RT_DIR=../../runtime make clean --silent
LG_RT_DIR=../../runtime make $MAKE_FLAGS --silent

# ##########################################################################
# END COMPILATION STAGE
# ##########################################################################

echo "RUN_STATUS=COMPILED"

# ##########################################################################
# RUN STAGE
# Please extract your time measurement into RESULT variable.
# Feel free to create other outputs such as profiling results
# They will be accessible in the 3x run folder.
# ##########################################################################

MPIRUN="mpirun --host n0000,n0001,n0002,n0003 -np 4 --bind-to none"
FLAGS="-npp 512 -wpp 512 -l 256"
PROF_FLAGS="-level 2 -cat legion_prof -logfile prof_% -hl:prof 4"
CAPTURE_TIME="grep 'ELAPSED TIME' | awk -F= '{print $2}'"

RESULT=$($MPIRUN ./ckt_sim $FLAGS $PROF_FLAGS | $CAPTURE_TIME)

# ##########################################################################
# END RUN STAGE
# ##########################################################################

echo "RUN_STATUS=RUN"

echo "time: $RESULT"