#!/bin/bash

# Hyperion Task Template

set -e

# ##########################################################################
# MODULE DEPENDENCIES
# Please ensure you're loading all required modules here.
# ##########################################################################

source /usr/local/modules-3.2.10/init/bash

module load mpi/openmpi/1.8.2
module load gasnet/1.22.4-openmpi

# ##########################################################################
# COMPILATION STAGE
# The root folder of legion is available in $LG_DIR.
# Please ensure you're loading all required modules yourself.
# Clean your build target or you might be running an outdated build
# ##########################################################################

rm -rf fuzz-tester
git clone https://github.com/StanfordLegion/fuzz-tester.git
cd fuzz-tester

# ##########################################################################
# END COMPILATION STAGE
# ##########################################################################

echo "RUN_STATUS=COMPILED"

# ##########################################################################
# RUN STAGE
# Please extract time measurements into the RESULT variable.
# Feel free to create other outputs such as profiling results
# They will be accessible in the 3x run folder.
# ##########################################################################

LG_RT_DIR=$LG_DIR/runtime python main.py

# ##########################################################################
# END RUN STAGE
# ##########################################################################

echo "RUN_STATUS=RUN"

return 0
