#!/bin/bash

# Hyperion Task Template

set -e

# ##########################################################################
# MODULE DEPENDENCIES
# Please ensure you're loading all required modules here.
# ##########################################################################

source /usr/local/modules-3.2.10/init/bash

module load mpi/openmpi/1.8.2
module load gasnet/1.22.4-openmpi

# ##########################################################################
# COMPILATION STAGE
# You're in the root folder of the legion runtime
# Please ensure you're loading all required modules yourself.
# Clean your build target or you might be running an outdated build
# ##########################################################################

cd examples/full_circuit

LG_RT_DIR=../../runtime make clean --silent
LG_RT_DIR=../../runtime make DEBUG=0 SHARED_LOWLEVEL=0 USE_GASNET=1 --silent

# ##########################################################################
# END COMPILATION STAGE
# ##########################################################################

echo "RUN_STATUS=COMPILED"

# ##########################################################################
# RUN STAGE
# Please extract time measurement into RESULT variable.
# Feel free to create other outputs such as profiling results
# They will be accessible in the 3x run folder.
# ##########################################################################

MPIRUN="mpirun --host n0000,n0001,n0002,n0003 -np 4 --bind-to none"
CKT_SIM_FLAGS="-npp 512 -wpp 512 -l 256"

RESULT=$($MPIRUN ./ckt_sim $CKT_SIM_FLAGS | grep "ELAPSED TIME" | awk -F= '{print $2}')

# ##########################################################################
# END RUN STAGE
# ##########################################################################

echo "RUN_STATUS=RUN"

echo "time: $RESULT"